before:
  hooks:
    - go mod tidy

release:
  prerelease: auto

builds:
  - binary: tsk
    id: linux
    main: ./cmd/tsk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - >-
        -s -w
        -X "main.version={{.Version}}"
        -X "main.commit={{.Commit}}"
  - binary: tsk
    id: macos
    main: ./cmd/tsk
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X "main.version={{.Version}}"
        -X "main.commit={{.Commit}}"
    hooks:
      post:
        - cmd: codesign -s {{ .Env.CODESIGN_IDENTITY }} {{ .Path }}
          output: true

archives:
  - builds:
      - linux
      - macos
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}arm_{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - completions/*

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/homebrew/
brews:
  - name: tsk
    homepage: "https://github.com/notnmeyer/tsk"
    description: "A simple task runner and build tool with TOML configuration."
    commit_author:
      name: tsk-bot
      email: 672246+notnmeyer@users.noreply.github.com
    repository:
      owner: notnmeyer
      name: homebrew-tsk
      token: "{{ .Env.HOMEBREW_TAP_REPO_GITHUB_TOKEN }}"
    skip_upload: auto
    install: |-
      bin.install "tsk"
      fish_completion.install "completions/tsk.fish"

# .goreleaser.yaml
npms:
  - name: "@notnmeyer/tsk"
    description: "A simple task runner and build tool with TOML configuration."
    homepage: https://notnmeyer.github.io/tsk-docs/docs/installation/
    keywords:
      - cli
      - make
      - task runner
      - taskrunner
    license: MIT
    email: 672246+notnmeyer@users.noreply.github.com
    repository: https://github.com/notnmeyer/tsk
    bugs: https://github.com/notnmeyer/tsk/issues

    # Additional files/globs you want to add to the package.
    #
    # Default: ["README*", "LICENSE*"]
    # Templates: allowed.
    extra_files:
      - glob: ./path/to/file.txt
        name_template: "file.txt"

    # Additional templated files to add to the app bundle.
    # Those files will have their contents pass through the template engine,
    # and its results will be added to the archive.
    # and/or to add more files.
    #
    # Templates: allowed.
    templated_extra_files:
      # src can also be a glob, as long as dst is a directory.
      - src: "LICENSE.md.tpl"
        dst: LICENSE.md

    # Access level: public or restricted.
    access: public

    # Package format: tar, tgz, tar.gz, zip, or binary.
    #
    # Required: if more than one archive format is being used.
    format: tgz

    # Allows to further filter the artifacts.
    #
    # Artifacts that do not match this expression will be ignored.
    #
    # Templates: allowed.
    if: '{{ eq .Os "linux" }}'

    # Disables the configuration.
    # Any value different of 'true' will be considered 'false'.
    #
    # Templates: allowed.
    disable: "{{ gt .Patch 0 }}"

    # URL which is determined by the given Token (github, gitlab or gitea).
    #
    # Default depends on the client.
    # Templates: allowed.
    # Since: v2.10.
    url_template: "https://github.mycompany.com/foo/bar/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
