before:
  hooks:
    - go mod tidy

release:
  prerelease: auto

builds:
  - binary: tsk
    id: linux
    main: ./cmd/tsk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - >-
        -s -w
        -X "main.version={{.Version}}"
        -X "main.commit={{.Commit}}"
  - binary: tsk
    id: macos
    main: ./cmd/tsk
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X "main.version={{.Version}}"
        -X "main.commit={{.Commit}}"
    hooks:
      post:
        - cmd: codesign -s {{ .Env.CODESIGN_IDENTITY }} {{ .Path }}
          output: true

archives:
  - builds:
      - linux
      - macos
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}arm_{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - completions/*

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/homebrew/
brews:
  - name: tsk
    homepage: "https://github.com/notnmeyer/tsk"
    description: "A simple task runner and build tool with TOML configuration."
    commit_author:
      name: tsk-bot
      email: 672246+notnmeyer@users.noreply.github.com
    repository:
      owner: notnmeyer
      name: homebrew-tsk
      token: "{{ .Env.HOMEBREW_TAP_REPO_GITHUB_TOKEN }}"
    skip_upload: auto
    install: |-
      bin.install "tsk"
      fish_completion.install "completions/tsk.fish"
