[tasks.build]
cmds = [
  "go build -o bin/tsk -v cmd/tsk/*.go"
]

[tasks.clean]
cmds = [
  "rm -rf ./dist/*"
]

[tasks.release]
dotenv = ".env"
deps = [["test"]]

[tasks.release_dry]
dotenv = ".env"
cmds = [
  "goreleaser release --clean --skip-publish --skip-validate"
]

[tasks.test]
cmds = ["go test ./..."]

[tasks.deps]
cmds = ["go mod tidy"]

[tasks.install_release]
env = { version = "0.3.0", platform = "Macos", arch = "arm64" }

[tasks.sign]
dotenv = ".env"
cmds = [
  "gon gon-arm64.hcl",
  "gon gon-amd64.hcl",
]
