[tasks]

  [tasks.build]
  cmds = [
    "goreleaser build --single-target --snapshot --rm-dist"
  ]

  [tasks.release]
  cmds = [
    "goreleaser release"
  ]

  [tasks.test]
  cmds = ["go test ./..."]

  [tasks.deps]
  cmds = ["go mod tidy"]

  [tasks.clean]
  cmds = [
    "rm -f tsk",
    "rm -rf dist"
  ]
