[tasks.run]
cmds = [
  "go run cmd/tsk/tsk.go {{.CLI_ARGS}}"
]
[tasks.build]
cmds = [
  "go build -o bin/tsk -v cmd/tsk/tsk.go"
]

[tasks.clean]
cmds = [
  "rm -rf ./dist/*"
]

[tasks.release]
description = '''
Create a release (locally, no CI).

usage: version=0.0.0 tsk release
'''
dotenv = ".env"

[tasks.release_ci]
description = '''
Create and push a new tag to GitHub, triggering a new release from CI.

usage: `tsk release_ci -- v0.0.0`
'''
cmds = [
  "git tag {{.CLI_ARGS}}",
  "git push origin {{.CLI_ARGS}}",
]

[tasks.release_dry]
dotenv = ".env"
cmds = [
  "goreleaser release --clean --skip-publish --skip-validate"
]

[tasks.test]
cmds = ["go test ./... {{.CLI_ARGS}}"]

[tasks.deps]
cmds = ["go mod tidy"]

[tasks.install_release]
# see scripts/install_release.sh for configurable env arguments
description = '''
Downloads the specified release and installs it to ~/bin.

usage: version=0.8.1 platform=Darwin arch=arm64 tsk install_release
'''

[tasks.sign]
dotenv = ".env"
cmds = [
  "gon gon-arm64.hcl",
  "gon gon-amd64.hcl",
]

[tasks.install_completions]
description = "install shell completions"
cmds = [
  "cp completions/tsk.fish ~/.config/fish/completions/"
]
