[tasks.run]
desc = "Run tsk"
cmds = [
  "go run cmd/tsk/tsk.go {{.CLI_ARGS}}"
]

[tasks.build]
desc = "Build the project"
cmds = [
  "go build -o bin/tsk -v cmd/tsk/tsk.go"
]

[tasks.clean]
desc = "Remove build artifacts"
cmds = [
  "rm -rf ./dist/*"
]

[tasks.release]
desc = "Trigger a release"
description = '''
Create and push a new tag to GitHub, triggering a new release from CI.

usage: `tsk release -- v0.0.0`
'''
cmds = [
  "git tag {{.CLI_ARGS}}",
  "git push origin {{.CLI_ARGS}}",
]

[tasks.release_dry]
desc = "goreleaser dry run"
dotenv = ".env"
cmds = [
  "goreleaser release --clean --skip-publish --skip-validate"
]

[tasks.test]
desc = "Run tests"
cmds = ["go test ./... -cover {{.CLI_ARGS}}"]

[tasks.deps]
desc = "Install deps"
cmds = ["go mod tidy"]

[tasks.install_release]
# see scripts/install_release.sh for configurable env arguments
desc = "Install a tsk version"
description = '''
Downloads the specified release and installs it to ~/bin.

usage: version=0.8.1 platform=Darwin arch=arm64 tsk install_release
'''

[tasks.sign]
desc = "Sign binaries"
dotenv = ".env"
cmds = [
  "gon gon-arm64.hcl",
  "gon gon-amd64.hcl",
]

[tasks.install_completions]
desc = "Install shell completions"
cmds = [
  "cp completions/tsk.fish ~/.config/fish/completions/"
]
