[tasks]

  [tasks.build]
  cmds = ["go build cmd/tsk/*.go"]

  [tasks.test]
  cmds = ["go test ./..."]

  [tasks.deps]
  cmds = ["go mod tidy"]

  [tasks.clean]
  cmds = [
    "rm -f tsk",
    "rm -rf dist"
  ]
