[tasks.build]
cmds = [
  "goreleaser build --single-target --snapshot --clean --output bin/tsk"
]

[tasks.release]
cmds = [
  "git tag -a v${VERSION}",
  "git push --tags",
  "goreleaser release --clean",
]

[tasks.release_dry]
cmds = [
  "goreleaser release --clean --skip-publish --skip-validate"
]

[tasks.test]
cmds = ["go test ./..."]

[tasks.deps]
cmds = ["go mod tidy"]

[tasks.clean]
cmds = [
  "rm -f tsk",
  "rm -rf dist"
]
