[tasks.run]
cmds = [
  "go run cmd/tsk/tsk.go {{.CLI_ARGS}}"
]
[tasks.build]
cmds = [
  "go build -o bin/tsk -v cmd/tsk/*.go"
]

[tasks.clean]
cmds = [
  "rm -rf ./dist/*"
]

[tasks.release]
dotenv = ".env"

[tasks.release_dry]
dotenv = ".env"
cmds = [
  "goreleaser release --clean --skip-publish --skip-validate"
]

[tasks.test]
cmds = ["go test ./... {{.CLI_ARGS}}"]

[tasks.deps]
cmds = ["go mod tidy"]

[tasks.install_release]
# see scripts/install_release.sh for configurable env arguments

[tasks.sign]
dotenv = ".env"
cmds = [
  "gon gon-arm64.hcl",
  "gon gon-amd64.hcl",
]
