[tasks.setup1]
cmds = ["sleep 1", "echo 'doing setup1...'"]

[tasks.setup2]
cmds = ["echo 'doing setup2...'"]

[tasks.setup3]
cmds = ["echo 'doing setup3...'"]

[tasks.main]
deps = [
  ["setup1", "setup2"],
  ["setup3"]
]
cmds = ["echo 'running main...'"]
