[tasks]

  [tasks.hello_world]
  cmds = [
    "echo \"hello world\"",
  ]

  [tasks.pwd]
  dir = "/tmp"
  cmds = [
    "echo \"my pwd is $(pwd)\"",
  ]

  # this task executes `scripts/no_cmd.sh`
  [tasks.no_cmd]
  env = {GREETING = "Hello"}

