name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install notnmeyer/tsk/tsk
      - env:
          BURNTSUSHI_TOML_110: ""
        run: tsk test
